apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: myappdbs.mongodb.cloud-ninja.name
spec:
  group: mongodb.cloud-ninja.name
  names:
    kind: MyAppDB
    listKind: MyAppDBList
    plural: myappdbs
    singular: myappdb
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
