apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: myapp-operator
  template:
    metadata:
      labels:
        name: myapp-operator
    spec:
      serviceAccountName: myapp-operator
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          # Replace this with the built image name
          image: quay.io/jauskaln/nodejs-operator:v0.1.6
          imagePullPolicy: 'Always'
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          # Replace this with the built image name
          image: quay.io/jauskaln/nodejs-operator:v0.1.6
          imagePullPolicy: 'Always'
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "myapp-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
      volumes:
        - name: runner
          emptyDir: {}
